server:
  grpc_addr: ":9090"
  http_addr: ":8080"

database:
  dsn: "postgres://aeibi:password@127.0.0.1:5432/aeibi?sslmode=disable"
  migrations_source: "file://internal/repository/db/migration"

oss:
  endpoint: ""
  access_key: ""
  secret_key: ""
  bucket: "aeibi"
  use_ssl: false

auth:
  jwt_secret: ""
  jwt_issuer: "aeibi"
  jwt_ttl: "10s"
  refresh_ttl: "720h"
